### PR TITLE
Add unit tests to client

### PR DESCRIPTION
**Pull request by marcorossi5**

### CODE REVIEW

**Comment by scarrazza** [comment]
Thanks @marcorossi5, now this repo is public and I have activated codecov and precommit.

**Comment by scarrazza** [comment]
@marcorossi5 just another couple of requests:
- could you please replace in all places TiiQ with TII-QRC?
- I think it would be useful to include some technical docs explaining how to use this library and the content of the library. For example a simple sphinx page, with installation instructions, a short tutorial and the api reference should be sufficient. Could you please grab the setup in qibo* and try to port here, maybe in another PR?

**Comment by marcorossi5** [comment]
Let me replace TiiQ with TII-QRC. Then, if you agree, we can merge and open a new PR to address the second point.

Do you want to keep `TIIProvider` as the client class name? or do you want me to change it?

**Comment by scarrazza** [comment]
Great, thanks. I think we can keep `TIIProvider` for now.

**Review by scarrazza — APPROVED** [review]

**Comment by marcorossi5** [comment]
What about the package name? `qibo_tii_provider` still works?

**Comment by scarrazza** [comment]
Let me think but meanwhile let's keep as it is. I just prefer to avoid using TiiQ in the docs.

**Pull request merged**
